#!/bin/sh
VIRTUALBOX_ID="$(cat .vagrant/machines/default/virtualbox/id)" &&
    vboxmanage list vms |
    awk "{ match(\$0, /\"(.+)\"\\s\\{$VIRTUALBOX_ID\\}/, name); if (length(name[1]) > 0) { print name[1] } }"
